force-app/main/default/objects/Product__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is product Active ?</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>description of product</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>Price for products</description>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ProductList.cls
/**
 * @Author          :   Ashita
 * @Date            :   Dec 11
 * @Description     :   Controller Class for LWC COmponent
 */
public with sharing class ProductList {
    public ProductList() {} 

    /**
     * Methodto be used by LWC
     */
    @AuraEnabled(cacheable=true)
    public static List<Product__c> getProductList() {
        return [SELECT Id, Name,  Active__c, Description__c , price__c FROM Product__c Order By CreatedDate DESC];
    }

}